### ISSUE TITLE
rootfs2image build error

### ISSUE THREAD

**Issue by mri-scanomat** [lueschem/edi-pi#11]
Hi @lueschem 

First of all, thanks for a great framework. It solved a lot of issues for us and it gives the amount of control we need for our IOT devices. So that is all great :) 

But we bumped into an issue in the image create process. When we stated to add our own playbooks and installing additional packages in the image, the rootfs2image script would throw an error during the rsync step saying : "Not enough disk space!". 

From what we could figure out, It looks like the calculate of the sector count for the image `dd if=/dev/zero of="${RPI_IMAGE}" bs=512 count=${IMAGE_SECTORS}` is wrong. My guess is that If the data sector increases in size the total size will get larges that the allocated size, which then results in the above error. 

We solved the error by increasing the calculated size of `DATA_SECTORS` apply the same logic as for `ROOT_SECTORS` and add 25%, so the resulting code looks like 
`DATA_SECTORS=$(expr $(expr ${DATA_PARTITION_SIZE_M}  + ${DATA_PARTITION_SIZE_M} \/ 100 \* 25) \* 1024 \* 1024 \/ 512)`

We are not sure if this is the correct approach or not, so we decided not to convert I to a pull request until we got some feedback from you on the issue.

Are we onto the right approach here or is something else causing the error?

Best Regards
Michael

**Comment by lueschem** [comment]
Hi Michael

Cool - I am happy to hear that edi is useful for your project.

I will need to take a closer look at it. Usually I have almost no data on the "data partition" (basically I just store the settings there that needs to survive an upgrade, see also https://www.get-edi.io/assets/pdfs/EfficientDebian.pdf, What partition layout shall I choose?).

Would it also be possible to just assign more Mb to the data partition? E.g.:
DATA_PARTITION_SIZE_M=512
We could even make the data partition size configurable.

Best regards
Matthias
