### ISSUE TITLE
Image Size is too big

### ISSUE THREAD

**Issue by ohdearaugustin** [lueschem/edi-pi#28]
Rsync in rootfs2image in the postprocessing doesn't use -H (preserve hard links). Most of the shared libraries at /usr/lib/aarch64-linux-gnu/ use hardlinks. So the caculation of the image size then fails.

Easy to fix add -H to rsync in rootfs2image.

**Comment by lueschem** [comment]
Very good catch! Thanks a lot for finding and resolving that issue!

**Comment by lueschem** [comment]
I added the following test for that issue: https://github.com/lueschem/edi-ci-public/blob/main/tests/test_hardlink.py
